### ISSUE TITLE
Install fails due to deps

### ISSUE THREAD

**Issue by nomysz** [osx-cross/homebrew-avr#323]
Mac M1 Sonoma 14.2.1 (23C71)

```❯ brew install avr-gdb
==> Fetching dependencies for osx-cross/avr/avr-gdb: python@3.9
==> Fetching python@3.9
==> Downloading https://ghcr.io/v2/homebrew/core/python/3.9/manifests/3.9.18_2
Already downloaded: /Users/my-user/Library/Caches/Homebrew/downloads/a9d0e3ef285399164b30b3fbf1431f3d265ff072cfc9a9c3bd364b3dd0f74094--python@3.9-3.9.18_2.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/python/3.9/blobs/sha256:adbbe4d4fd80b70e40cb7a233d2d5f5dda88bdc274deb153
Already downloaded: /Users/my-user/Library/Caches/Homebrew/downloads/a5efbea1955f1777304de5280bc4bf272c2cc341806b6186fad4737730009e46--python@3.9--3.9.18_2.arm64_sonoma.bottle.tar.gz
==> Fetching osx-cross/avr/avr-gdb
==> Downloading https://raw.githubusercontent.com/osx-cross/homebrew-avr/18d50ba2a168a3b90a25c96e4bc4c053df77d7dc/Patch/a
Already downloaded: /Users/my-user/Library/Caches/Homebrew/downloads/0ca5d8e65886bc674f0ba0ec9f98e4b657920f87f9784a16f9fca756681475b3--avr-binutils-elf-bfd-gdb-fix.patch
==> Downloading https://ftp.gnu.org/gnu/gdb/gdb-10.1.tar.xz
Already downloaded: /Users/my-user/Library/Caches/Homebrew/downloads/d6dfd55ca620ab89b3209b96be8cac6a9b85c636faf527f4c5e4bc7e7ff07cee--gdb-10.1.tar.xz
==> Installing avr-gdb from osx-cross/avr
==> Installing dependencies for osx-cross/avr/avr-gdb: python@3.9
==> Installing osx-cross/avr/avr-gdb dependency: python@3.9
==> Downloading https://ghcr.io/v2/homebrew/core/python/3.9/manifests/3.9.18_2
Already downloaded: /Users/my-user/Library/Caches/Homebrew/downloads/a9d0e3ef285399164b30b3fbf1431f3d265ff072cfc9a9c3bd364b3dd0f74094--python@3.9-3.9.18_2.bottle_manifest.json
==> Pouring python@3.9--3.9.18_2.arm64_sonoma.bottle.tar.gz
==> /opt/homebrew/Cellar/python@3.9/3.9.18_2/bin/python3.9 -Im ensurepip
Last 15 lines from /Users/my-user/Library/Logs/Homebrew/python@3.9/post_install.01.python3.9:
  File "/opt/homebrew/Cellar/python@3.9/3.9.18_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.9/3.9.18_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/homebrew/Cellar/python@3.9/3.9.18_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ensurepip/__main__.py", line 5, in <module>
    sys.exit(ensurepip._main())
  File "/opt/homebrew/Cellar/python@3.9/3.9.18_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ensurepip/__init__.py", line 211, in _main
    return _bootstrap(
  File "/opt/homebrew/Cellar/python@3.9/3.9.18_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ensurepip/__init__.py", line 130, in _bootstrap
    return _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
  File "/opt/homebrew/Cellar/python@3.9/3.9.18_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ensurepip/__init__.py", line 39, in _run_pip
    return subprocess.run(cmd, check=True).returncode
  File "/opt/homebrew/Cellar/python@3.9/3.9.18_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/opt/homebrew/opt/python@3.9/bin/python3.9', '-I', '-c', '\nimport runpy\nimport sys\nsys.path = [\'/private/tmp/tmpr1gb2etk/setuptools-68.2.2-py3-none-any.whl\', \'/private/tmp/tmpr1gb2etk/pip-23.3.1-py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'/private/tmp/tmpr1gb2etk\', \'setuptools\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 1.
Warning: The post-install step did not complete successfully
You can try again using:
  brew postinstall python@3.9
==> Summary
🍺  /opt/homebrew/Cellar/python@3.9/3.9.18_2: 2,921 files, 54.8MB
==> Installing osx-cross/avr/avr-gdb
==> Patching
==> Applying avr-binutils-elf-bfd-gdb-fix.patch
patching file 'bfd/elf-bfd.h'
==> ../configure --target=avr --prefix=/opt/homebrew/Cellar/avr-gdb/10.1 --disable-debug --disable-dependency-tracking --
==> make
Last 15 lines from /Users/my-user/Library/Logs/Homebrew/avr-gdb/02.make:
checking whether to use MPFR... auto
checking for libmpfr... yes
checking how to link with libmpfr... -lmpfr -lgmp
checking whether to use python... /opt/homebrew/opt/python@3.9/bin/python3.9
Traceback (most recent call last):
  File "/private/tmp/avr-gdb-20240126-70685-wx6tsf/gdb-10.1/build/gdb/../../gdb/python/python-config.py", line 7, in <module>
    from distutils import sysconfig
  File "/opt/homebrew/Cellar/python@3.9/3.9.18_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 88, in create_module
    return importlib.import_module('setuptools._distutils')
  File "/opt/homebrew/Cellar/python@3.9/3.9.18_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'setuptools'
configure: error: failure running python-config --includes
make[1]: *** [configure-gdb] Error 1
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/osx-cross/homebrew-avr/issues
```

**Comment by ladislas** [comment]
it should be fixed, feel free to reopen if needed
